import type { CSSProperties } from "react";

import { colors, spacing } from "@hellobeauty/design-tokens";

export function stack(gap: string): CSSProperties {
  return {
    display: "grid",
    gap,
  };
}

export const miniEditorialStyles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#F8FAFC",
    backgroundImage:
      "linear-gradient(180deg, #F9F8F6 0%, #FFFFFF 42%, #F8FAFC 100%)",
    padding: `calc(${spacing.xl} + env(safe-area-inset-top)) ${spacing.lg} calc(104px + env(safe-area-inset-bottom))`,
    color: colors.miniText,
    boxSizing: "border-box",
  } as CSSProperties,
  header: {
    display: "grid",
    gap: spacing.xs,
    marginBottom: spacing.lg,
  } as CSSProperties,
  eyebrow: {
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: colors.miniMuted,
  } as CSSProperties,
  title: {
    fontSize: "32px",
    lineHeight: 1.08,
    fontWeight: 400,
    fontFamily: '"Iowan Old Style", "Palatino Linotype", "Book Antiqua", "Songti SC", serif',
    color: colors.miniText,
  } as CSSProperties,
  body: {
    fontSize: "14px",
    lineHeight: 1.75,
    color: colors.miniMuted,
  } as CSSProperties,
  panel: {
    display: "grid",
    gap: spacing.sm,
    padding: spacing.lg,
    backgroundColor: colors.miniSurface,
    border: `1px solid ${colors.line}`,
    boxSizing: "border-box",
  } as CSSProperties,
  softPanel: {
    display: "grid",
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.miniSurfaceMuted,
    border: `1px solid ${colors.line}`,
    boxSizing: "border-box",
  } as CSSProperties,
  label: {
    fontSize: "12px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: colors.miniMuted,
  } as CSSProperties,
  input: {
    width: "100%",
    padding: "14px 0",
    fontSize: "16px",
    lineHeight: 1.4,
    color: colors.miniText,
    borderBottom: `1px solid ${colors.lineStrong}`,
  } as CSSProperties,
  primaryButton: {
    height: "48px",
    padding: `0 ${spacing.md}`,
    border: `1px solid ${colors.miniPrimary}`,
    borderRadius: "9999px",
    backgroundColor: colors.miniPrimary,
    color: colors.miniPage,
    fontSize: "14px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    justifySelf: "center",
    margin: "0 auto",
    textAlign: "center",
  } as CSSProperties,
  secondaryButton: {
    height: "48px",
    padding: `0 ${spacing.md}`,
    border: `1px solid ${colors.lineStrong}`,
    borderRadius: "9999px",
    backgroundColor: "transparent",
    color: colors.miniText,
    fontSize: "14px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    justifySelf: "center",
    margin: "0 auto",
    textAlign: "center",
  } as CSSProperties,
  tertiaryButton: {
    height: "44px",
    padding: `0 ${spacing.md}`,
    border: `1px solid ${colors.line}`,
    borderRadius: "9999px",
    backgroundColor: colors.miniSurface,
    color: colors.miniText,
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    justifySelf: "center",
    margin: "0 auto",
    textAlign: "center",
  } as CSSProperties,
  imageFrame: {
    overflow: "hidden",
    border: `1px solid ${colors.line}`,
    backgroundColor: colors.miniSurface,
  } as CSSProperties,
  portraitPreviewWrap: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  } as CSSProperties,
  portraitPreviewFrame: {
    width: "220px",
    maxWidth: "100%",
    height: "292px",
    overflow: "hidden",
    border: `1px solid ${colors.line}`,
    backgroundColor: colors.miniSurface,
  } as CSSProperties,
  portraitPreviewImage: {
    width: "100%",
    height: "100%",
  } as CSSProperties,
  exportPhotoFrame: {
    width: "326px",
    maxWidth: "100%",
    boxSizing: "border-box",
    border: `1px solid ${colors.line}`,
    borderRadius: "4px",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    position: "relative",
    margin: "0 auto",
  } as CSSProperties,
  exportPhotoFrameSpacer: {
    width: "100%",
    paddingTop: "133.3333%",
  } as CSSProperties,
  exportPhotoFrameInner: {
    position: "absolute",
    left: "12px",
    right: "12px",
    top: "12px",
    bottom: "12px",
    display: "flex",
    alignItems: "stretch",
    justifyContent: "stretch",
  } as CSSProperties,
  exportPhotoImage: {
    width: "100%",
    height: "100%",
    borderRadius: "4px",
    backgroundColor: "rgba(28, 28, 28, 0.04)",
  } as CSSProperties,
  portraitThumbRail: {
    display: "flex",
    gap: spacing.sm,
    flexWrap: "wrap",
  } as CSSProperties,
  portraitThumbFrame: {
    width: "72px",
    height: "96px",
    overflow: "hidden",
    border: `1px solid ${colors.line}`,
    backgroundColor: colors.miniSurface,
  } as CSSProperties,
  portraitThumbImage: {
    width: "100%",
    height: "100%",
  } as CSSProperties,
  previewCard: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: spacing.sm,
    boxSizing: "border-box",
    overflow: "hidden",
  } as CSSProperties,
  previewMetaText: {
    width: "100%",
    padding: `0 ${spacing.xs}`,
    boxSizing: "border-box",
    fontSize: "14px",
    lineHeight: 1.75,
    color: colors.miniMuted,
    textAlign: "center",
    wordBreak: "break-all",
  } as CSSProperties,
  previewActionWrap: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
  } as CSSProperties,
  selectionSummaryRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  } as CSSProperties,
  selectAllToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  } as CSSProperties,
  selectAllIndicator: {
    width: "18px",
    height: "18px",
    borderRadius: "999px",
    border: `2px solid ${colors.miniPrimary}`,
    backgroundColor: "transparent",
    boxSizing: "border-box",
    flexShrink: 0,
  } as CSSProperties,
  selectAllIndicatorActive: {
    backgroundColor: colors.miniPrimary,
  } as CSSProperties,
  actionButtonRow: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: spacing.sm,
    alignItems: "center",
  } as CSSProperties,
  magazineHero: {
    position: "relative",
    display: "grid",
    gap: spacing.md,
    minHeight: "360px",
    padding: `${spacing.lg} ${spacing.md}`,
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: "#FFFDFA",
    overflow: "hidden",
    boxSizing: "border-box",
  } as CSSProperties,
  heroImageFrame: {
    position: "relative",
    width: "100%",
    height: "240px",
    overflow: "hidden",
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: "#E9EEF5",
  } as CSSProperties,
  heroImage: {
    width: "100%",
    height: "100%",
  } as CSSProperties,
  heroKickerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  } as CSSProperties,
  issueStamp: {
    minWidth: "64px",
    minHeight: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: colors.miniPrimary,
    color: colors.miniPage,
    fontSize: "13px",
    lineHeight: 1.2,
    textAlign: "center",
  } as CSSProperties,
  deckText: {
    fontSize: "15px",
    lineHeight: 1.72,
    color: "#334155",
  } as CSSProperties,
  parallaxBand: {
    position: "relative",
    display: "grid",
    gap: spacing.sm,
    padding: spacing.md,
    borderLeft: "4px solid #1e3a5f",
    background:
      "linear-gradient(135deg, rgba(30, 58, 95, 0.09), rgba(59, 130, 246, 0.04))",
    overflow: "hidden",
  } as CSSProperties,
  optionCard: {
    display: "grid",
    gap: spacing.sm,
    padding: spacing.md,
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: "#FFFFFF",
    boxSizing: "border-box",
  } as CSSProperties,
  optionCardDark: {
    display: "grid",
    gap: spacing.sm,
    padding: spacing.md,
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: colors.miniPrimary,
    color: colors.miniPage,
    boxSizing: "border-box",
  } as CSSProperties,
  optionTitle: {
    fontSize: "20px",
    lineHeight: 1.2,
    fontWeight: 500,
    color: colors.miniText,
    fontFamily: '"Iowan Old Style", "Palatino Linotype", "Songti SC", serif',
  } as CSSProperties,
  optionTitleInverse: {
    fontSize: "20px",
    lineHeight: 1.2,
    fontWeight: 500,
    color: colors.miniPage,
    fontFamily: '"Iowan Old Style", "Palatino Linotype", "Songti SC", serif',
  } as CSSProperties,
  microCaption: {
    fontSize: "11px",
    lineHeight: 1.55,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#64748B",
  } as CSSProperties,
  microCaptionInverse: {
    fontSize: "11px",
    lineHeight: 1.55,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "rgba(249, 248, 246, 0.76)",
  } as CSSProperties,
  bottomDock: {
    position: "fixed",
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
    zIndex: 50,
    display: "grid",
    gridTemplateColumns: "1fr 1.4fr 1fr",
    gap: "1px",
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: colors.miniPrimary,
  } as CSSProperties,
  dockItem: {
    minHeight: "52px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFDFA",
    color: colors.miniText,
    fontSize: "12px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  } as CSSProperties,
  dockItemPrimary: {
    minHeight: "52px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.miniPrimary,
    color: colors.miniPage,
    fontSize: "12px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  } as CSSProperties,
  sessionStrip: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: spacing.sm,
    alignItems: "center",
    padding: `${spacing.sm} 0`,
    borderTop: `1px solid ${colors.lineStrong}`,
    borderBottom: `1px solid ${colors.lineStrong}`,
  } as CSSProperties,
  liveStage: {
    display: "grid",
    gap: spacing.md,
    padding: spacing.md,
    minHeight: "330px",
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: "#101820",
    color: "#F8FAFC",
    boxSizing: "border-box",
  } as CSSProperties,
  liveStatusCard: {
    minHeight: "260px",
    display: "grid",
    alignItems: "center",
    justifyItems: "center",
    gap: spacing.sm,
    border: "1px solid rgba(248, 250, 252, 0.28)",
    background:
      "linear-gradient(135deg, rgba(30, 58, 95, 0.6), rgba(16, 24, 32, 0.94))",
    padding: spacing.md,
    textAlign: "center",
  } as CSSProperties,
  countdownText: {
    fontSize: "72px",
    lineHeight: 1,
    fontWeight: 400,
    fontFamily: '"Iowan Old Style", "Palatino Linotype", "Songti SC", serif',
    color: "#FFFFFF",
  } as CSSProperties,
  liveRail: {
    display: "flex",
    gap: spacing.sm,
    overflowX: "auto",
    paddingBottom: spacing.xs,
    WebkitOverflowScrolling: "touch",
  } as CSSProperties,
  liveRailCard: {
    width: "208px",
    flexShrink: 0,
    display: "grid",
    gap: spacing.xs,
    padding: spacing.sm,
    border: `1px solid ${colors.line}`,
    backgroundColor: "#FFFDFA",
    boxSizing: "border-box",
  } as CSSProperties,
  utilityRow: {
    display: "flex",
    gap: spacing.sm,
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
  } as CSSProperties,
  segmentedControl: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    border: `1px solid ${colors.miniPrimary}`,
    backgroundColor: colors.miniPrimary,
    gap: "1px",
  } as CSSProperties,
  segmentItem: {
    minHeight: "48px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: `0 ${spacing.xs}`,
    backgroundColor: "#FFFFFF",
    color: colors.miniText,
    fontSize: "12px",
    textAlign: "center",
  } as CSSProperties,
  segmentItemActive: {
    minHeight: "48px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: `0 ${spacing.xs}`,
    backgroundColor: colors.miniPrimary,
    color: colors.miniPage,
    fontSize: "12px",
    textAlign: "center",
  } as CSSProperties,
  divider: {
    height: "1px",
    backgroundColor: colors.line,
    width: "100%",
  } as CSSProperties,
} as const;
